# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Jason Yu
email: me@ycmjason.com
description: > # this means to ignore newlines until "baseurl:"
  Jason Yu is a passionate real-life problem solver and musician.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.ycmjason.com" # the base hostname & protocol for your site
twitter_username: ycmjason
github_username:  ycmjason

# Build settings
markdown: kramdown
